# -*- coding: utf-8 -*-
"""regression_nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcHTSi-skYKxeI3zhOqWIrk3n7q9yfvO
"""

!pip install opendatasets

import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import opendatasets as od

od.download("https://www.kaggle.com/datasets/andonians/random-linear-regression")

data=pd.read_csv("random-linear-regression/test.csv")

data.head()

data.shape

x = data['x']
y = data['y']

y

plt.scatter(x,y, c='b')
plt.show()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train.shape, x_test.shape

plt.scatter(x_train, y_train, c='b' ,label='training data')
plt.scatter(x_test, y_test, c='y', label='test data')
plt.legend()
plt.show()

"""Model bulding"""

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64,input_shape=[1]),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.05),
              metrics = ['mae'])
epoch_number=10
history= model.fit(tf.expand_dims(x_train, axis=-1), y_train, epochs=epoch_number)

model.summary()

y_prediction=model.predict(x_test)
y_prediction[:5]

y_test.head(5)

plt.scatter(x_train, y_train, c='b', label='tainning data')
plt.scatter(x_test, y_test, c='y', label='test data')
plt.scatter(x_test, y_prediction, c='r', label='prediction data')
plt.legend()
plt.show()

model.evaluate(x_test, y_test)

mae = tf.reduce_mean(tf.abs(tf.constant(y_test, dtype=tf.float32) - tf.squeeze(y_prediction)))
mae

mse = tf.reduce_mean(tf.square(tf.constant(y_test, dtype=tf.float32) - tf.squeeze(y_prediction)))
print("Mean Squared Error:", mse.numpy())

history.history

x_range=range(1,epoch_number+1)
loss=history.history['loss']
plt.plot(x_range, history.history['loss'])
plt.xlabel('epoch')
plt.ylabel('loss')
plt.show()